
apiVersion: batch/v1
kind: Job
metadata:
  name: hydrus-job-template
spec:
  template:
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: <nfs-pvc-name>
      containers:
      - name: hydrus
        image: watermodelling/hydrus-job:latest
        imagePullPolicy: Alawys
        args: ["hflow-job-execute", "<task_id>", "<redis_url>"]
        volumeMounts:
        - mountPath: /workspace
          name: nfs-vol
          subPath: /<project>/hydrus/<model_name>
      restartPolicy: Never
  backoffLimit: 1